// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hosts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHost = `-- name: CreateHost :one
INSERT INTO hosts (name, ip)
VALUES ($1, $2)
RETURNING id, name, ip, created_at
`

type CreateHostParams struct {
	Name string
	Ip   string
}

func (q *Queries) CreateHost(ctx context.Context, arg CreateHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, createHost, arg.Name, arg.Ip)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHost = `-- name: DeleteHost :execrows
DELETE FROM hosts
WHERE id = $1
`

func (q *Queries) DeleteHost(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHost = `-- name: GetHost :one
SELECT id, name, ip, created_at FROM hosts
WHERE id = $1
`

func (q *Queries) GetHost(ctx context.Context, id pgtype.UUID) (Host, error) {
	row := q.db.QueryRow(ctx, getHost, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const listHosts = `-- name: ListHosts :many
SELECT id, name, ip, created_at FROM hosts
ORDER BY created_at
`

func (q *Queries) ListHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.Query(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHost = `-- name: UpdateHost :one
UPDATE hosts
SET name = $2, ip = $3
WHERE id = $1
RETURNING id, name, ip, created_at
`

type UpdateHostParams struct {
	ID   pgtype.UUID
	Name string
	Ip   string
}

func (q *Queries) UpdateHost(ctx context.Context, arg UpdateHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, updateHost, arg.ID, arg.Name, arg.Ip)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}
