// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instances.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInstance = `-- name: CreateInstance :one
INSERT INTO instances 
(host_id, port, max_players, dedicated_ram_mb, log_path)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, host_id, port, max_players, dedicated_ram_mb, log_path, created_at, status
`

type CreateInstanceParams struct {
	HostID         pgtype.UUID
	Port           int32
	MaxPlayers     int32
	DedicatedRamMb int32
	LogPath        string
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, createInstance,
		arg.HostID,
		arg.Port,
		arg.MaxPlayers,
		arg.DedicatedRamMb,
		arg.LogPath,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Port,
		&i.MaxPlayers,
		&i.DedicatedRamMb,
		&i.LogPath,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const deleteInstance = `-- name: DeleteInstance :execrows
DELETE FROM instances
WHERE id = $1
`

func (q *Queries) DeleteInstance(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInstance, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInstance = `-- name: GetInstance :one
SELECT id, host_id, port, max_players, dedicated_ram_mb, log_path, created_at, status FROM instances
WHERE id = $1
`

func (q *Queries) GetInstance(ctx context.Context, id pgtype.UUID) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstance, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Port,
		&i.MaxPlayers,
		&i.DedicatedRamMb,
		&i.LogPath,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const listInstances = `-- name: ListInstances :many
SELECT id, host_id, port, max_players, dedicated_ram_mb, log_path, created_at, status FROM instances
ORDER BY created_at DESC
`

func (q *Queries) ListInstances(ctx context.Context) ([]Instance, error) {
	rows, err := q.db.Query(ctx, listInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Port,
			&i.MaxPlayers,
			&i.DedicatedRamMb,
			&i.LogPath,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstance = `-- name: UpdateInstance :one
UPDATE instances
SET 
host_id             = $2,
port                = $3,
max_players         = $4,
dedicated_ram_mb    = $5,
log_path            = $6
WHERE id            = $1
RETURNING id, host_id, port, max_players, dedicated_ram_mb, log_path, created_at, status
`

type UpdateInstanceParams struct {
	ID             pgtype.UUID
	HostID         pgtype.UUID
	Port           int32
	MaxPlayers     int32
	DedicatedRamMb int32
	LogPath        string
}

func (q *Queries) UpdateInstance(ctx context.Context, arg UpdateInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, updateInstance,
		arg.ID,
		arg.HostID,
		arg.Port,
		arg.MaxPlayers,
		arg.DedicatedRamMb,
		arg.LogPath,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Port,
		&i.MaxPlayers,
		&i.DedicatedRamMb,
		&i.LogPath,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}
