// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type InstanceStatus string

const (
	InstanceStatusONLINE   InstanceStatus = "ONLINE"
	InstanceStatusOFFLINE  InstanceStatus = "OFFLINE"
	InstanceStatusSTARTING InstanceStatus = "STARTING"
)

func (e *InstanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InstanceStatus(s)
	case string:
		*e = InstanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InstanceStatus: %T", src)
	}
	return nil
}

type NullInstanceStatus struct {
	InstanceStatus InstanceStatus
	Valid          bool // Valid is true if InstanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInstanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InstanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InstanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInstanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InstanceStatus), nil
}

type Host struct {
	ID        pgtype.UUID
	Name      string
	Ip        string
	CreatedAt pgtype.Timestamptz
}

type Instance struct {
	ID             pgtype.UUID
	HostID         pgtype.UUID
	Port           int32
	MaxPlayers     int32
	DedicatedRamMb int32
	LogPath        string
	CreatedAt      pgtype.Timestamptz
	Status         InstanceStatus
}
